//
// **** AUTOMATICALLY GENERATED BY mk-node-decls.pl -- DO NOT EDIT ****
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace gr8 {
class block_node; 
class identity_node; 
class read_node; 
class post_node; 
class function_definition_node; 
class stop_node; 
class null_node; 
class return_node; 
class evaluation_node; 
class again_node; 
class address_of_node; 
class if_else_node; 
class index_node; 
class variable_declaration_node; 
class function_declaration_node; 
class if_node; 
class alloc_node; 
class tweet_node; 
class function_invocation_node; 
class sweeping_node; 

} // namespace gr8

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_gr8_NODE_ALLNODES_H__
#define __AUTOMATIC_gr8_NODE_ALLNODES_H__

#include "ast/block_node.h"
#include "ast/identity_node.h"
#include "ast/read_node.h"
#include "ast/post_node.h"
#include "ast/function_definition_node.h"
#include "ast/stop_node.h"
#include "ast/null_node.h"
#include "ast/return_node.h"
#include "ast/evaluation_node.h"
#include "ast/again_node.h"
#include "ast/address_of_node.h"
#include "ast/if_else_node.h"
#include "ast/index_node.h"
#include "ast/variable_declaration_node.h"
#include "ast/function_declaration_node.h"
#include "ast/if_node.h"
#include "ast/alloc_node.h"
#include "ast/tweet_node.h"
#include "ast/function_invocation_node.h"
#include "ast/sweeping_node.h"


#endif /* !defined(__AUTOMATIC_gr8_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */
