// **** AUTOMATICALLY GENERATED BY mk-visitor-decls.pl -- DO NOT EDIT ****
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__

#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__

  virtual void do_block_node(gr8::block_node *const node, int lvl) = 0;
  virtual void do_identity_node(gr8::identity_node *const node, int lvl) = 0;
  virtual void do_read_node(gr8::read_node *const node, int lvl) = 0;
  virtual void do_post_node(gr8::post_node *const node, int lvl) = 0;
  virtual void do_function_definition_node(gr8::function_definition_node *const node, int lvl) = 0;
  virtual void do_stop_node(gr8::stop_node *const node, int lvl) = 0;
  virtual void do_null_node(gr8::null_node *const node, int lvl) = 0;
  virtual void do_return_node(gr8::return_node *const node, int lvl) = 0;
  virtual void do_evaluation_node(gr8::evaluation_node *const node, int lvl) = 0;
  virtual void do_again_node(gr8::again_node *const node, int lvl) = 0;
  virtual void do_address_of_node(gr8::address_of_node *const node, int lvl) = 0;
  virtual void do_if_else_node(gr8::if_else_node *const node, int lvl) = 0;
  virtual void do_index_node(gr8::index_node *const node, int lvl) = 0;
  virtual void do_variable_declaration_node(gr8::variable_declaration_node *const node, int lvl) = 0;
  virtual void do_function_declaration_node(gr8::function_declaration_node *const node, int lvl) = 0;
  virtual void do_if_node(gr8::if_node *const node, int lvl) = 0;
  virtual void do_alloc_node(gr8::alloc_node *const node, int lvl) = 0;
  virtual void do_tweet_node(gr8::tweet_node *const node, int lvl) = 0;
  virtual void do_function_invocation_node(gr8::function_invocation_node *const node, int lvl) = 0;
  virtual void do_sweeping_node(gr8::sweeping_node *const node, int lvl) = 0;


#else

  void do_block_node(gr8::block_node *const node, int lvl);
  void do_identity_node(gr8::identity_node *const node, int lvl);
  void do_read_node(gr8::read_node *const node, int lvl);
  void do_post_node(gr8::post_node *const node, int lvl);
  void do_function_definition_node(gr8::function_definition_node *const node, int lvl);
  void do_stop_node(gr8::stop_node *const node, int lvl);
  void do_null_node(gr8::null_node *const node, int lvl);
  void do_return_node(gr8::return_node *const node, int lvl);
  void do_evaluation_node(gr8::evaluation_node *const node, int lvl);
  void do_again_node(gr8::again_node *const node, int lvl);
  void do_address_of_node(gr8::address_of_node *const node, int lvl);
  void do_if_else_node(gr8::if_else_node *const node, int lvl);
  void do_index_node(gr8::index_node *const node, int lvl);
  void do_variable_declaration_node(gr8::variable_declaration_node *const node, int lvl);
  void do_function_declaration_node(gr8::function_declaration_node *const node, int lvl);
  void do_if_node(gr8::if_node *const node, int lvl);
  void do_alloc_node(gr8::alloc_node *const node, int lvl);
  void do_tweet_node(gr8::tweet_node *const node, int lvl);
  void do_function_invocation_node(gr8::function_invocation_node *const node, int lvl);
  void do_sweeping_node(gr8::sweeping_node *const node, int lvl);


#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */

#endif /* __IN_VISITOR_HEADER__ */
