//
// **** AUTOMATICALLY GENERATED BY mk-node-decls.pl -- DO NOT EDIT ****
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace simple {
class program_node; 
class read_node; 
class print_node; 
class evaluation_node; 
class while_node; 
class if_else_node; 
class if_node; 

} // namespace simple

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_simple_NODE_ALLNODES_H__
#define __AUTOMATIC_simple_NODE_ALLNODES_H__

#include "ast/program_node.h"
#include "ast/read_node.h"
#include "ast/print_node.h"
#include "ast/evaluation_node.h"
#include "ast/while_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"


#endif /* !defined(__AUTOMATIC_simple_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */
