// **** AUTOMATICALLY GENERATED BY mk-visitor-decls.pl -- DO NOT EDIT ****
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__

#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__

  virtual void do_program_node(simple::program_node *const node, int lvl) = 0;
  virtual void do_read_node(simple::read_node *const node, int lvl) = 0;
  virtual void do_print_node(simple::print_node *const node, int lvl) = 0;
  virtual void do_evaluation_node(simple::evaluation_node *const node, int lvl) = 0;
  virtual void do_while_node(simple::while_node *const node, int lvl) = 0;
  virtual void do_if_else_node(simple::if_else_node *const node, int lvl) = 0;
  virtual void do_if_node(simple::if_node *const node, int lvl) = 0;


#else

  void do_program_node(simple::program_node *const node, int lvl);
  void do_read_node(simple::read_node *const node, int lvl);
  void do_print_node(simple::print_node *const node, int lvl);
  void do_evaluation_node(simple::evaluation_node *const node, int lvl);
  void do_while_node(simple::while_node *const node, int lvl);
  void do_if_else_node(simple::if_else_node *const node, int lvl);
  void do_if_node(simple::if_node *const node, int lvl);


#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */

#endif /* __IN_VISITOR_HEADER__ */
